### ISSUE TITLE
Duvida Instalando com o composer

### ISSUE THREAD

**Issue by rstriquer** [pagarme/pagarme-core-api-php#18]
A página de bibliotecas da documentação aponta para este projeto, mas ele não possui um pacote composer para uso. Estou tentando configurar para fazer uso deste repositório, deixe a configuração como abaixo:
```JSON
"repositories": {
    "repo": {
        "type": "git",
        "url": "git@github.com:pagarme/pagarme-core-api-php.git"
    }
}
```

Mas mesmo configurando a opção `"tags-path": "v5.1.0"` ainda assim o mesmo erro me aparece 
```bash
[InvalidArgumentException]                                                                                                                                                      
  Could not find a matching version of package pagarme/pagarme-core-api-php. Check the package spelling, your version constraint and that the package is available in a stabilit  
  y which matches your minimum-stability (stable). 
```

Por acaso a arecomendação para uso com o composer é seguir utilizando o `pagarme/pagarme-php`? Se sim, qual a diferença?

Alguém conseguiu utilizar este repostório com o composer? Como fez?

Obrigado.

**Comment by alvaro-canepa** [comment]
Hi @rstriquer I think the problem was on packagist registration.
`pagarme/pagarme-php` has max version of 4.1.2 (https://packagist.org/packages/pagarme/pagarme-php)
`pagarme/pagarmecoreapi` has max version of 5.2.0 (https://packagist.org/packages/pagarme/pagarmecoreapi)

So, the correct composer call must be `composer require pagarme/pagarmecoreapi`
